### ISSUE TITLE
Создает ложный файл Found.txt и BASE.txt

### ISSUE THREAD

**Issue by Ss048** [phrutis/Rotor#10]
Привет phrutis!
Тестирую периодически программу. И при каждом запуске спустя разный промежуток времени происходит обновление файлов Found.txt и BASE.txt При этом адреса пустые, получается ложные срабатывания. Адресов почти 7 млн, если быть точным то 6,966,126. В чем может быть причина? Команда для запуска Rotor3.exe -m 2 -f sort6966126.bin

**Comment by Ss048** [comment]
Вот так в файле выглядит то что находит
==================================================================================
TIME: 2021-12-10 11:35:42
PRIV: a11a39a4a41f7c88ed0e98f60282365ad08584fb507173beb6717725b8e3fe20
PUBK: 0433061c9f92239a550cb852b8d2e3b034894677e9c4ba1eee06ec207184827f25c3dd530b07b2105cf91a5b12103a7c95105561cd4f122215da2ffe8cef7c010d
HASH: 52a80ad4c40ca0713884495c2a3c7de1ff4e5ab7
ADDR: 18Y3iWqW146ky2u2uAwKfJ8J1QLLtjuMGu
SALT: a11a39a4a41f7c88ed0e98f60282365ad08584fb507173beb6717725b8c40229
OFST: 2096118
GPUH: 3b4df4363caa9e3bd9da58020d3080be8230a4ae

**Comment by phrutis** [comment]
Привет! Прочти внимательно маин до конца!

- При использовании большого файла адресов (25млн. и больше) в режиме both происходят ложноположительные срабатывания найденных адресов. 
- Примерно 20 ложных адресов на 20.000.000.000 хешей. 
- В связи с этим отключил вывод информации о найденном хэше на экран.
- Для удобства сделал вывод в 2 файла Found.txt и BASE.txt
- В файле Found.txt только адреса, в файле BASE.txt вся информация.
- Сделано это для удобства, копируем адреса из файла Found.txt и вставляем их в окно проверки адресов списком на сайте. 
- К примеру на сайтах: https://www.homebitcoin.com/easybalance/ или https://bitcoindata.science/bitcoin-balance-check.html или http://addresschecker.eu
- Можете найти свои сайты для проверки списком. Желательно проверять на двух разных сайтах, для точности.
- Файл gpu.cl нужен, без него не работает!
- С базой до 5.000.000 адресов, ложноположительные срабатывания не обнаружены.

**Comment by Ss048** [comment]
Привет, читал. Подрезать базу наверно попробую, отпишусь тогда. Спасибо

**Comment by phrutis** [comment]
Этот Ротор медленный и прожерлевый в ресурсах пк.
Я бы рекомендовал посмотреть в сторону Rotor-Cuda, он работает намного быстрее, много доп. функций и не так греет карту. 
В Rotor-Cuda стоит двойная проверкой bloom фильтра на ложноположительное срабатывание. 
Это полностью исключает погрешность Error 0,0000100000
Если Cuda не поддерживается и подходит именно это Ротор можно поступить так:
1. Уменьшить базу, убрав из неё не сжатые адреса. Искать только сжатые адреса -m 1.
2. Если есть желание искать не сжатые. Можно запустить копиию программы -m 0 и искать только не сжатые адреса.
В этом случае общая скорость двух копий будет быстрее чем одна с -m 2. 
Теоритически базы станут меньше, возможно не будут выдаваться ложноподожительные результаты.

**Comment by Ss048** [comment]
Гоняю и Ротор и Rotor-Cuda. Спасибо за подсказки.

**Comment by Ss048** [comment]
Скажи, где можно реализовать такую фишку***, на примере команды Rotor-Cuda покажу:
Rotor-Cuda.exe -t 3 -m addresses --coin BTC --range 00FB6CC56FE8FD829EC5DAFFA7C32761AA5ACCA09782974921C411F2E499E4E5:01EB029B84177AEFCE7C06FCB267FCCEE6A641896F074507A5356EBA7E4503EB -i sorthash2400621.bin -b -r 10 -w+ c18fd43bb4c444efe20f55f4e0e6e2f555e31048
*** теперь собственно описание фишки, в команде прописывать такое значение -w это получается шаг, либо -w+ плюсуем либо -w- минусуем. Сложения и вычетания происходят в заданном диапозоне --range. само значение -w выбирается самостоятельно.
Логика такая:
00FB6CC56FE8FD829EC5DAFFA7C32761AA5ACCA09782974921C411F2E499E4E5 + c18fd43bb4c444efe20f55f4e0e6e2f555e31048 получили число
к полученному числу снова + c18fd43bb4c444efe20f55f4e0e6e2f555e31048 и так, пока укладываемся в диапозон до 
01EB029B84177AEFCE7C06FCB267FCCEE6A641896F074507A5356EBA7E4503EB
Можешь такое добавить в Rotor-Cuda или Rotor или LostCoins

**Comment by Ss048** [comment]
Получается, прошло сложение или вычитание,
 получилось значение программа проверила с базой и дальше и так пока не дойдет до конца диапозона. У тебя сейчас везде рандом в заданных диапозонах либо просто рандом.

**Comment by phrutis** [comment]
Это не сложно, можно сделать, есть много нюансов.

1.Это никому не нужно. Если добавлять всё что предлагают пользователи можно запутаться в ненужных режимах.
Обычно это происходит так, просят, сделай такое... 
Я оцениваю, говорю что такая функция интересная или это фигня (трата времени). Сделай это мне надо, для своих тестов и все!
Сделал, добавил. Человек попробовал убедился что это фигня и забыл, после этого даже не отписывается что там как, не закрывает тему, просто пропадает. 
Это 9/10 случаев. 
2.Это называется шаг. 
Нюансы:
Минусовать шагом от конечного хеша гипотетически можно. Но склалярное умножение всё равно будет плюсовать.
FFFFFFF000 - шаг w-1000000000 = EFFFFFF000
К EFFFFFF001 будет добавлятся +1,1,1..... 
 Следующий шаг от EFFFFFF001 отнимится 1000000000 будет DFFFFFF001 +1,+1,+1....

Логичнее добавлять 1 + 1000000000 +1,+1,+1,.....
2000000001,3000000001
Обновлять шаг теоритически можно через -r 1 +1000000000 значений.
Для GPU grid 256,256 и-r 1 каждые 2 секунды будет создаваться 65536 шагов +1000000000, 2000000000, 3000000000 к каждому будет добавляться +1,+1,+1...,  убрать скалярное умножение векторов пока не получается.После добавления -r 1 (+1000000000 значений), продолжить шагать от последнего 65536-го шага.

На процессоре в LostCoins можно ~~без скалярки +1,+1~~, просто шагать большими шагами w+ )
Одно ядро делает примерно 30,000 шагов в сек., 6 ядер 200,000 шагов в сек. 
Не вижу логического смысла в этой функции.
Рандом + значения это практически теже шаги что ты предлагаешь.

**Comment by Ss048** [comment]
Вот как раз бы для GPU grid 256,256 реализовать бы такое, было бы отлично. Именно нужно заданное число плюсовать, а не ровные. "убрать скалярное умножение векторов пока не получается" это помеха по любому будет, вся затея теряется.
Услышал тебя, буду думать где и как это можно реализовать.
Если разберешься с "убрать скалярное умножение векторов пока не получается" дай знать, тогда имеет смысл такое сделать.
Спасибо

**Comment by phrutis** [comment]
Без скалярки на GPU CUDA скорость упадёт более чем в 1000 раз. 
Тому пример CPU одно ядро с умнажением 3Mk/s и 30-50Kk/s без него.
Попробуй --stride в [BitCrack2](https://github.com/kanhavishva/BitCrack2) - он работает так же как Ротор без куды.

**Comment by Ss048** [comment]
Привет phrutis! Еще вопрос, в начале запуска всегда обновляет файлы Found.txt и BASE.txt, для чего это?
Базу адресов уменьшил, теперь все норм.

**Comment by phrutis** [comment]
Стоит это
```
ffd = fopen(tmp, "w");
	if (ffd) {
		fwrite(buffer, n, 1, ffd);
		fclose(ffd);
	}
	ffd = fopen("Found.txt", "a");
	if (ffd) {
		fwrite(buffer, n, 1, ffd);
		fclose(ffd);
	}
	free(info);
```
Видимо проверка возможность записать в файлы, а второй дописать. Согласен это лишнее.

**Comment by Ss048** [comment]
Пусть будет, просто решил уточнить нормально ли это или нет
