### ISSUE TITLE
Random

### ISSUE THREAD

**Issue by Delti42** [phrutis/Rotor#8]
Привет! Отличная работа. Но предлагаю, добавить возможность рандомного хеша внутри определенного диапозона. Есть ли возможность сделать это?

**Comment by phrutis** [comment]
Были такие предложения от других пользователей. 
Сделать параметр и указывать внутри какого диапазоне рандомить сложно.
Пробовал, сделать диапазонный параметр как в Rotor-Cuda -n 256. Была попытка среза рандомной 256-ти битной строки на куски, с округлением в  4 бита. То есть, срезать хеш на 4,8,16,20,24... бита (4 бита это один знак в хеше (0-f)) 
Проблема заключается в том что Ротор рандомит по всему диапозону 256-1. Чаще всего он выбирает 256-252, но когда генератор опускается ниже, хеш на 1-2 знака становится короче. А это уже другой диапазон. Сейчас пытаюсь сделать срез с правой стороны. Если  получится, потестю и залью. Не обещаю, следи за обновлениями.

**Comment by Delti42** [comment]
> Были такие предложения от других пользователей.
> Сделать параметр и указывать внутри какого диапазоне рандомить сложно.
> Пробовал, сделать диапазонный параметр как в Rotor-Cuda -n 256. Была попытка среза рандомной 256-ти битной строки на куски, с округлением в 4 бита. То есть, срезать хеш на 4,8,16,20,24... бита (4 бита это один знак в хеше (0-f))
> Проблема заключается в том что Ротор рандомит по всему диапозону 256-1. Чаще всего он выбирает 256-252, но когда генератор опускается ниже, хеш на 1-2 знака становится короче. А это уже другой диапазон. Сейчас пытаюсь сделать срез с правой стороны. Если получится, потестю и залью. Не обещаю, следи за обновлениями.

За фолловил! Буду следить за обновлениями. Но могу точно сказать, что это точно лучше чем bitCrack :)

**Comment by phrutis** [comment]
Есть предложения реализации по твоему вопросу. [смотри здесь](https://github.com/brichard19/BitCrack/issues/313#issuecomment-894791443)

**Comment by Delti42** [comment]
Привет! А на выходе в файле base.txt есть просто hash и gpuh чем они отличаются?

**Comment by phrutis** [comment]
HASH: Хеш bitcoin адреса в формате RIPEMD-160

GPUH: Хеш bitcoin адреса RIPEMD-160, вычисленный на GPU, всегда должен быть равен HASH

**Comment by phrutis** [comment]
Удалось реализовать эту функцию в другой программе [LostCoins](https://github.com/phrutis/LostCoins)
